# Generated by Django 4.1 on 2022-08-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_product_product_image_alter_product_id_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="Product_images/"),
        ),
    ]
