# Generated by Django 4.1 on 2022-08-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_product_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_id",
        ),
    ]
