# Generated by Django 4.1 on 2022-08-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_product_product_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("madhya pradesh", "madhya pradesh"),
                            ("bihar", "bihar"),
                            ("gujrat", "gujrat"),
                        ],
                        max_length=50,
                    ),
                ),
                ("gender", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("pimage", models.ImageField(blank=True, upload_to="pimage")),
                ("rdoc", models.FileField(blank=True, upload_to="rdocs")),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="product_description",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="product_is_active",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="product_stock",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
