# Generated by Django 4.1 on 2022-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_profile_product_product_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="productsimage")),
                ("details", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("discount", models.IntegerField()),
                ("final_price", models.IntegerField()),
            ],
        ),
    ]
